name: Docker Build & Push

on:
  push:
    tags:
      - "v*.*.*"   # dispara quando criar tag como v1.0.0
    branches:
      - main       # opcional: também buildar na main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extrair versão da tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/meu-app:${{ env.VERSION }} .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/meu-app:${{ env.VERSION }}

      - name: Push da imagem 'latest' (opcional)
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:latest
